# Generated by Django 3.1 on 2021-09-30 14:08

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='balance',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.DateField(verbose_name=django.utils.translation.ugettext_lazy),
        ),
    ]
