# Generated by Django 3.1 on 2021-10-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211008_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foundPoints',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
