# Generated by Django 3.0.6 on 2022-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221104_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='correction',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='injuries',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lostOfHumanlifes',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proceedings',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
