# Generated by Django 3.1 on 2021-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
