# Generated by Django 3.1 on 2021-10-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211021_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='foundPoints',
        ),
    ]
