# Generated by Django 3.1 on 2022-04-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220426_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
        ),
    ]
