# Generated by Django 3.1 on 2021-10-01 11:27

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211001_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.DateField(verbose_name=django.utils.translation.ugettext_lazy),
        ),
    ]
