# Generated by Django 3.1 on 2022-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
