# Generated by Django 3.1 on 2021-10-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211022_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectPictures', to='api.project'),
        ),
    ]
