# Generated by Django 3.1 on 2021-10-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_picture_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
