# Generated by Django 3.1 on 2022-05-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220523_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.company'),
        ),
    ]
