# Generated by Django 3.1 on 2022-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220422_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
