# Generated by Django 3.1 on 2022-06-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220601_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='first_name',
        ),
    ]
