# Generated by Django 3.1 on 2022-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_company_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fixed',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
