# Generated by Django 3.1 on 2022-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='read',
            new_name='fixed',
        ),
    ]
