# Generated by Django 3.1 on 2022-07-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
