# Generated by Django 3.1 on 2022-07-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
