# Generated by Django 3.1 on 2022-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220704_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='platform',
            field=models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('telegram', 'Telegram')], max_length=255, null=True, verbose_name='PLATFORM'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.BooleanField(default=1),
        ),
    ]
